### ISSUE TITLE
Transfer from 3m to 8m or from 8m to 3m?

### ISSUE THREAD

**Issue by wenshuaizhao** [starry-sky6688/DyMA-CL#2]
Hi, thanks for your contribution. I just started to reimplement this repo. However, I am a little confused about the training. 

As we are going to transfer from few to more. Why do we first train the 8m task?

**Comment by starry-sky6688** [comment]
Because DyMA-CL require the same action space between the maps, and we use zero-padding, there is a problem for transferring model from '3m' to '8m'. In '3m', the last 5 actions have never be chosen, so their Q-value is far from true value, when we use the model of '3m' on '8m', we find the performance of transferring is negative. Therefore, we transfer the model from '8m' to '3m' to avoid this problem. If you want to transfer from 3m  to 8m, you need to modify the source code of SMAC to unify the action space for all the maps.
